AWSTemplateFormatVersion: "2010-09-09"
Description: Create an S3 bucket for Lambda deployment packages

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: healthaura-dev-lambda-code-bucket
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Purpose
          Value: LambdaCodeStorage

  LambdaCodeBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LambdaCodeBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${LambdaCodeBucket}/*"

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref LambdaCodeBucket
    Export:
      Name: Healthaura-Dev-LambdaCodeBucket-Name