version: 3

env:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel
  TOKEN_SERVICE_ROOT: .

tasks:
  generate:
    desc: run all code generators
    cmds: 
      - task: openapi:generate

  openapi:generate:
    summary: Generate proto buffer definitions
    silent: true
    cmds:
      - echo Generating proto buffers...
      - |
        oapi-codegen -config ./openapi.gen.yml ./openapi.yaml
        mv stubs.gen.go ./gen/go/v1

  configure:sso:
    desc: Configure AWS SSO credentials
    cmds:
      - >
        aws configure sso 
        --endpoint-url https://healthaura.awsapps.com/start 
        --region us-east-1 
        --profile AWSAdministratorAccess-713881787612

  cf:
    desc: Package and deploy CloudFormation infrastructure
    cmds:
      - task: package:cloudformation
      - task: deploy:cloudformation

  package:cloudformation:
    summary: Package CloudFormation Infrastructure
    silent: true
    cmds:
      - echo Packaging CloudFormation Stack...
      - |
        aws cloudformation package --template-file ./cloudformation/main.yaml --s3-bucket healthaura-dev-shared-infrastructure --output-template-file ./cloudformation/packaged.yaml --profile AWSAdministratorAccess-713881787612

  deploy:cloudformation:
    summary: Deploy CloudFormation Infrastructure
    silent: true
    cmds:
      - echo Deploying CloudFormation Stack...
      - |
        aws cloudformation deploy --template-file /Users/bricealdrich/Development/github.com/healthaura/token-service/cloudformation/packaged.yaml --stack-name token-service-stack  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND