version: 3

env:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel
  TOKEN_SERVICE_ROOT: .

tasks:
  build:
    desc: Build the project
    cmds:
      - |
        GOOS=linux GOARCH=amd64 go build -o bootstrap
        chmod +x bootstrap
        mv bootstrap ./lambda/
        cd lambda
        zip lambda.zip bootstrap
  generate:
    desc: run all code generators
    cmds: 
      - task: openapi:generate

  ent:generate:
    summary: Generate ent database code from the schema definitions
    silent: true
    cmds:
      - echo Generating ent schema...
      - |
        go generate ./entgenerator

  openapi:generate:
    summary: Generate proto buffer definitions
    silent: true
    cmds:
      - echo Generating proto buffers...
      - |
        oapi-codegen -config ./openapi.gen.yml ./openapi.yaml
        mv stubs.gen.go ./gen/go/v1

  cf:
    desc: Package and deploy CloudFormation infrastructure
    cmds:
      - task: package:cloudformation
      - task: deploy:cloudformation

  package:cloudformation:
    summary: Package CloudFormation Infrastructure
    silent: true
    cmds:
      - echo Packaging CloudFormation Stack...
      - |
        aws cloudformation package --template-file ./cloudformation/main.yaml --s3-bucket healthaura-dev-shared-infrastructure --output-template-file ./cloudformation/packaged.yaml --profile AWSAdministratorAccess-713881787612

  deploy:cloudformation:
    summary: Deploy CloudFormation Infrastructure
    silent: true
    cmds:
      - echo Deploying CloudFormation Stack...
      - |
        aws cloudformation deploy --template-file /Users/bricealdrich/Development/github.com/healthaura/token-service/cloudformation/packaged.yaml --stack-name token-service-stack  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND